name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Go
              uses: actions/setup-go@v5  
              with: 
                go-version: 1.23.0
            
            - name: Run Build Command
              run: scripts/buildprod.sh

            - name: Authenticate with GCP
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v2'

            - name: Use gcloud CLI
              run: gcloud info
            
            - name: Authenticate Docker with Google Artifact Registry
              run: gcloud auth configure-docker asia-south1-docker.pkg.dev

            - name: Build Docker image and push to Google Artifact Registry
              run: gcloud builds submit --tag asia-south1-docker.pkg.dev/notely-cd-bootdev/notely-ar-repo/notely:latest .
